#!/usr/bin/bash
dists=(
    darwin/amd64
    darwin/arm64
    linux/386
    linux/amd64
    linux/arm
    linux/arm64
    windows/386
    windows/amd64
    windows/arm64
)

root="$(dirname "$0")/.."
version="$(cat $root/.version)"
module="$(grep '^module ' $root/go.mod | awk '{print $2}')"
build_pkg="${module}/internal/build"

target="$1"
prefix="$2-"
target_path="cmd/$target/$target.go"
dist_path="$root/dist"

if [[ "$prefix" == "-" ]]; then
    prefix=""
fi

if [[ -z "$target" || ! -f "$target_path" ]]; then
    echo "Invalid target. Please specify one of the following targets:"
    (
        cd "$root/cmd"
        ls -d *
    )

    exit 1
fi

for dist in ${dists[@]}; do
    os_arch=(${dist//\// })
    echo "> Building $dist"

    env GOOS=${os_arch[0]} GOARCH=${os_arch[1]} CGO_ENABLED=0 go build -ldflags="-X $build_pkg.version=$version -X $build_pkg.release=true -extldflags=-static -s -w" -o "$dist_path/${prefix}${target}_${os_arch[0]}_${os_arch[1]}" "$target_path"
    if [[ ! $? -eq 0 ]]; then
        echo "Couldn't build for $dist."
    fi
done
